- install packages

In [2]:
import pandas as pd
import plotly.express as px

- read file

In [4]:
df = pd.read_csv("credit_cards.csv", sep=";", decimal=",")
df.head()

,Unnamed: 0,CUST_ID,BALANCE,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,BALANCE.1,PURCHASES.1,ONEOFF_PURCHASES.1,PURCHASES_INSTALLMENTS,CASH_ADVANCE.1,TENURE
0,NaN,C17342,27.625906,234.48,0.00,234.48,0.000000,0.0,12,2500.0,109.281131,93.624640,0.00,0.818182,1.000000,0.000000,1.000000,0.000000,12.0
1,NaN,C13053,8791.161142,0.00,0.00,0.00,3706.755143,4.0,0,12000.0,2244.627566,2916.278944,0.00,1.000000,0.000000,0.000000,0.000000,0.333333,12.0
2,NaN,C11723,165.808096,981.19,823.39,157.80,0.000000,0.0,16,9000.0,672.446893,105.350665,0.25,0.714286,0.714286,0.571429,0.285714,0.000000,7.0
3,NaN,C13717,4157.933876,929.20,631.40,297.80,2592.238013,8.0,12,8000.0,934.634439,1076.539881,0.00,1.000000,0.583333,0.333333,0.250000,0.583333,12.0
4,NaN,C11464,19.945714,170.00,170.00,0.00,0.000000,0.0,1,6500.0,734.613034,166.057617,1.00,0.272727,0.083333,0.083333,0.000000,0.000000,12.0

In [5]:
df = df.drop(columns=["Unnamed: 0"])
df.head()

,CUST_ID,BALANCE,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,BALANCE.1,PURCHASES.1,ONEOFF_PURCHASES.1,PURCHASES_INSTALLMENTS,CASH_ADVANCE.1,TENURE
0,C17342,27.625906,234.48,0.00,234.48,0.000000,0.0,12,2500.0,109.281131,93.624640,0.00,0.818182,1.000000,0.000000,1.000000,0.000000,12.0
1,C13053,8791.161142,0.00,0.00,0.00,3706.755143,4.0,0,12000.0,2244.627566,2916.278944,0.00,1.000000,0.000000,0.000000,0.000000,0.333333,12.0
2,C11723,165.808096,981.19,823.39,157.80,0.000000,0.0,16,9000.0,672.446893,105.350665,0.25,0.714286,0.714286,0.571429,0.285714,0.000000,7.0
3,C13717,4157.933876,929.20,631.40,297.80,2592.238013,8.0,12,8000.0,934.634439,1076.539881,0.00,1.000000,0.583333,0.333333,0.250000,0.583333,12.0
4,C11464,19.945714,170.00,170.00,0.00,0.000000,0.0,1,6500.0,734.613034,166.057617,1.00,0.272727,0.083333,0.083333,0.000000,0.000000,12.0

- check outliers, missing values & variability

In [6]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4700 entries, 0 to 4699
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CUST_ID                 4700 non-null   object
 1   BALANCE                 4697 non-null   float64
 2   PURCHASES               4694 non-null   float64
 3   ONEOFF_PURCHASES        4693 non-null   float64
 4   INSTALLMENTS_PURCHASES  4699 non-null   float64
 5   CASH_ADVANCE            4695 non-null   float64
 6   CASH_ADVANCE_TRX        4698 non-null   float64
 7   PURCHASES_TRX           4700 non-null   int64
 8   CREDIT_LIMIT            4700 non-null   float64
 9   PAYMENTS                4695 non-null   float64
 10  MINIMUM_PAYMENTS        4526 non-null   float64
 11  PRC_FULL_PAYMENT        4696 non-null   float64
 12  BALANCE.1               4698 non-null   float64
 13  PURCHASES.1             4696 non-null   float64
 14  ONEOFF_PURCHASES.1      4695 non-null   float64
 15  PURCHASES_INSTALLMENTS  4697 non-null   float64
 16  CASH_ADVANCE.1          4698 non-null   float64
 17  TENURE                  4697 non-null   float64
dtypes: float64(16), int64(1), object(1)
memory usage: 661.1+ KB

,BALANCE,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,BALANCE.1,PURCHASES.1,ONEOFF_PURCHASES.1,PURCHASES_INSTALLMENTS,CASH_ADVANCE.1,TENURE
count,4697.000000,4694.000000,4693.000000,4699.000000,4695.000000,4698.000000,4700.000000,4700.000000,4695.000000,4526.000000,4696.000000,4698.000000,4696.000000,4695.000000,4697.000000,4698.000000,4697.000000
mean,1605.946809,1006.578332,588.280424,419.199589,975.821152,3.203278,14.833191,4533.927369,1766.673895,936.281241,0.154930,0.876829,0.487583,0.201804,0.361547,0.134524,11.521397
std,2187.896959,2108.919333,1625.643256,959.024738,2211.503604,6.646826,25.558587,3729.725976,2951.572115,2776.063820,0.295154,0.237319,0.401264,0.297890,0.398668,0.199063,1.337293
min,-1.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,150.000000,0.000000,0.019163,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000
25%,131.342635,37.842500,0.000000,0.000000,0.000000,0.000000,1.000000,1600.000000,396.836709,170.443708,0.000000,0.888889,0.083333,0.000000,0.000000,0.000000,12.000000
50%,882.715792,360.050000,39.580000,84.000000,0.000000,0.000000,7.000000,3000.000000,864.527484,316.910039,0.000000,1.000000,0.500000,0.083333,0.166667,0.000000,12.000000
75%,2064.106212,1109.530000,585.630000,475.820000,1051.329594,4.000000,17.000000,6500.000000,1921.171023,858.239701,0.142857,1.000000,0.916667,0.285714,0.750000,0.250000,12.000000
max,19043.138560,41050.400000,40624.060000,22500.000000,47137.211760,123.000000,358.000000,30000.000000,40627.595240,76406.207520,1.000000,1.000000,1.000000,1.000000,1.000000,1.500000,12.000000

In [ ]:
# remove -1 (incorrect value)
df.replace(-1, pd.NA, inplace=True)

- check missing values

In [8]:
df.isnull().sum()

CUST_ID                     0
BALANCE                     4
PURCHASES                   7
ONEOFF_PURCHASES            7
INSTALLMENTS_PURCHASES      1
CASH_ADVANCE                5
CASH_ADVANCE_TRX            2
PURCHASES_TRX               0
CREDIT_LIMIT                0
PAYMENTS                    5
MINIMUM_PAYMENTS          174
PRC_FULL_PAYMENT            4
BALANCE.1                   2
PURCHASES.1                 4
ONEOFF_PURCHASES.1          5
PURCHASES_INSTALLMENTS      3
CASH_ADVANCE.1              2
TENURE                      3
dtype: int64

In [9]:
# make "MINIMUM_PAYMENTS" useable
df.replace(-1, pd.NA, inplace=True)

- correlation matrix

In [10]:
df.corr(numeric_only=True)

,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,BALANCE.1,PURCHASES.1,ONEOFF_PURCHASES.1,PURCHASES_INSTALLMENTS,CASH_ADVANCE.1,TENURE
ONEOFF_PURCHASES,1.000000,0.284090,-0.008326,-0.026999,0.547479,0.306910,0.534191,0.076624,0.142606,0.112934,0.264391,0.525800,0.120723,-0.068937,0.058769
INSTALLMENTS_PURCHASES,0.284090,1.000000,-0.058050,-0.075105,0.612953,0.286491,0.369157,0.142406,0.191847,0.114511,0.427448,0.209908,0.495137,-0.129471,0.079171
CASH_ADVANCE,-0.008326,-0.058050,1.000000,0.672758,-0.061747,0.312835,0.482010,0.131913,-0.141997,0.102462,-0.189465,-0.074124,-0.154535,0.618495,-0.061599
CASH_ADVANCE_TRX,-0.026999,-0.075105,0.672758,1.000000,-0.056073,0.179034,0.274520,0.119081,-0.176433,0.150020,-0.191581,-0.059477,-0.160474,0.805109,-0.037164
PURCHASES_TRX,0.547479,0.612953,-0.061747,-0.056073,1.000000,0.284029,0.367982,0.107084,0.184845,0.187764,0.561325,0.545037,0.523148,-0.120232,0.113736
CREDIT_LIMIT,0.306910,0.286491,0.312835,0.179034,0.284029,1.000000,0.427226,0.124698,0.059806,0.107150,0.128956,0.293709,0.076678,0.148267,0.127133
PAYMENTS,0.534191,0.369157,0.482010,0.274520,0.367982,0.427226,1.000000,0.143759,0.122094,0.060529,0.099590,0.236066,0.079495,0.192391,0.099264
MINIMUM_PAYMENTS,0.076624,0.142406,0.131913,0.119081,0.107084,0.124698,0.143759,1.000000,-0.131391,0.125857,0.005802,-0.031429,0.031649,0.093315,0.051852
PRC_FULL_PAYMENT,0.142606,0.191847,-0.141997,-0.176433,0.184845,0.059806,0.122094,-0.131391,1.000000,-0.094769,0.309637,0.179155,0.251354,-0.247128,-0.034508
BALANCE.1,0.112934,0.114511,0.102462,0.150020,0.187764,0.107150,0.060529,0.125857,-0.094769,1.000000,0.223180,0.199305,0.172540,0.197493,0.133274
PURCHASES.1,0.264391,0.427448,-0.189465,-0.191581,0.561325,0.128956,0.099590,0.005802,0.309637,0.223180,1.000000,0.498378,0.862586,-0.298320,0.063201
ONEOFF_PURCHASES.1,0.525800,0.209908,-0.074124,-0.059477,0.545037,0.293709,0.236066,-0.031429,0.179155,0.199305,0.498378,1.000000,0.138528,-0.105767,0.074657
PURCHASES_INSTALLMENTS,0.120723,0.495137,-0.154535,-0.160474,0.523148,0.076678,0.079495,0.031649,0.251354,0.172540,0.862586,0.138528,1.000000,-0.253257,0.074896
CASH_ADVANCE.1,-0.068937,-0.129471,0.618495,0.805109,-0.120232,0.148267,0.192391,0.093315,-0.247128,0.197493,-0.298320,-0.105767,-0.253257,1.000000,-0.127560
TENURE,0.058769,0.079171,-0.061599,-0.037164,0.113736,0.127133,0.099264,0.051852,-0.034508,0.133274,0.063201,0.074657,0.074896,-0.127560,1.000000

- export preprocessed dataset

In [12]:
df.to_csv("credit_cards_clean.csv", index=False)